/*
 * This source file was generated by the Gradle 'init' task
 */



// import org.example.list.LinkedList;


// import static org.example.utilities.StringUtils.join;
// import static org.example.utilities.StringUtils.split;

// import static org.example.app.MessageUtils.getMessage;
// import org.apache.commons.text.WordUtils;

// import Plants.*;
import DLC.*;

public class App {
    public static void main(String[] args) {

        System.out.println("ANJI");
        // LinkedList tokens;
        // tokens = split(getMessage());
        // String result = join(tokens);
        // System.out.println(WordUtils.capitalize(result));
    }
}
//? kita harus gradle build di file yg ada si buildny. 
